services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db

volumes:
  db_data: